#!/usr/bin/env bash
# Generate weekly metrics report locally
#
# Usage:
#   ./generate-weekly-report.sh [7d|30d] [--issue]
#
# Options:
#   7d|30d       Period for metrics (default: 30d)
#   --issue      Create GitHub issue with report (requires gh CLI)

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"

cd "$PROJECT_ROOT"

# Parse arguments
PERIOD="${1:-30d}"
CREATE_ISSUE=false

if [[ "${2:-}" == "--issue" ]]; then
  CREATE_ISSUE=true
fi

# Validate period
if [[ ! "$PERIOD" =~ ^(7d|30d)$ ]]; then
  echo "❌ Error: Period must be '7d' or '30d'" >&2
  exit 1
fi

echo "📊 Generating metrics report for period: $PERIOD"
echo ""

# Generate metrics
echo "🔍 Extracting metrics from session logs..."
METRICS_JSON=$(mktemp)
"$SCRIPT_DIR/metrics" "$PERIOD" > "$METRICS_JSON"

# Extract key metrics
WORKFLOWS=$(jq -r '.totalWorkflows' "$METRICS_JSON")
TIME_SAVED=$(jq -r '.totalTimeSaved / 60 | floor' "$METRICS_JSON")
TEMPLATE_RATE=$(jq -r '.templateUsage.rate | floor' "$METRICS_JSON")
EARLY_EXIT_RATE=$(jq -r '.earlyExit.rate | floor' "$METRICS_JSON")
EXPRESS_RATE=$(jq -r '.expressPlanning.rate | floor' "$METRICS_JSON")

echo "✓ Workflows analyzed: $WORKFLOWS"
echo "✓ Time saved: ${TIME_SAVED}h"
echo ""

# Generate dashboard
echo "📈 Generating dashboard report..."
"$SCRIPT_DIR/dashboard" < "$METRICS_JSON"

echo ""
echo "✅ Report generated: .ai/METRICS_REPORT.md"
echo ""

# Display summary
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📊 METRICS SUMMARY ($PERIOD)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  Workflows:        $WORKFLOWS"
echo "  Time Saved:       ${TIME_SAVED}h"
echo ""
echo "  OPTIMIZATION ADOPTION"
echo "  ├─ Templates:     ${TEMPLATE_RATE}% (target: 40%)"
echo "  ├─ Early Exit:    ${EARLY_EXIT_RATE}% (target: 30%)"
echo "  └─ Express:       ${EXPRESS_RATE}% (target: 15%)"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

# Create GitHub issue if requested
if [[ "$CREATE_ISSUE" == true ]]; then
  if ! command -v gh &> /dev/null; then
    echo "⚠️  Warning: gh CLI not found. Install from: https://cli.github.com/" >&2
    echo "    Skipping issue creation." >&2
  else
    echo "📝 Creating GitHub issue..."

    # Extract sections from report
    SUMMARY=$(awk '/## Executive Summary/,/---/' .ai/METRICS_REPORT.md | sed '1d;$d')
    RECOMMENDATIONS=$(awk '/## Recommendations/,/---/' .ai/METRICS_REPORT.md | sed '1d;$d')

    # Create issue body
    ISSUE_BODY=$(cat <<EOF
# 📊 Weekly Workflow Metrics Report

**Period**: $PERIOD (last $([ "$PERIOD" == "7d" ] && echo "7 days" || echo "30 days"))
**Generated**: $(date -u +%Y-%m-%d)

## 🎯 Key Metrics

| Metric | Value | Target |
|--------|-------|--------|
| Workflows Analyzed | $WORKFLOWS | - |
| Total Time Saved | ${TIME_SAVED}h | - |
| Template Usage | ${TEMPLATE_RATE}% | 40% |
| Early Exit Rate | ${EARLY_EXIT_RATE}% | 30% |
| Express Planning | ${EXPRESS_RATE}% | 15% |

## 📈 Executive Summary

$SUMMARY

## 💡 Recommendations

$RECOMMENDATIONS

## 📄 Full Report

View the complete metrics dashboard: [.ai/METRICS_REPORT.md](.ai/METRICS_REPORT.md)

---

*Generated by \`generate-weekly-report.sh\`*
EOF
)

    # Create issue
    gh issue create \
      --title "📊 Weekly Metrics Report - $(date -u +%Y-%m-%d)" \
      --body "$ISSUE_BODY" \
      --label "metrics,weekly-report"

    echo "✅ Issue created successfully"
  fi
fi

# Cleanup
rm -f "$METRICS_JSON"

echo ""
echo "Next steps:"
echo "  • Review the report: cat .ai/METRICS_REPORT.md"
echo "  • Commit changes: git add .ai/METRICS_REPORT.md && git commit"
if [[ "$CREATE_ISSUE" == false ]]; then
  echo "  • Create issue: $0 $PERIOD --issue"
fi
echo ""
