import { getValoraVersion } from 'utils/paths';

export const AI_DISCLOSURE_TEXT = `AI-generated by Valora. Review before use. EU AI Act Art. 50.`;

export function getDisclosureFooter(version: string): string {
	return `\n_AI-generated by Valora v${version}. Review before use. EU AI Act Art. 50._`;
}

export function getDisclosureFooterAuto(flags: { noDisclosure?: boolean } = {}): null | string {
	if (isDisclosureSuppressed(flags, process.env, process.argv)) return null;
	return getDisclosureFooter(getValoraVersion());
}

export function isDisclosureSuppressed(
	flags: { noDisclosure?: boolean },
	env: NodeJS.ProcessEnv,
	argv: string[] = []
): boolean {
	if (flags.noDisclosure === true) return true;
	if (env['VALORA_NO_DISCLOSURE'] === '1') return true;
	if (argv.includes('--no-disclosure')) return true;
	const outputIdx = argv.indexOf('--output');
	if (outputIdx !== -1 && (argv[outputIdx + 1] === 'json' || argv[outputIdx + 1] === 'yaml')) return true;
	return false;
}
