/**
 * Reads every agent definition under `packages/* /agents/*.md`, validates that
 * its `role` matches a key in `data/agents/registry.json`, and emits a
 * Markdown table suitable for embedding in `documentation/architecture/system-card.md`.
 *
 * Run via `pnpm exec tsx scripts/generate-system-card-agents.ts`.
 */

import matter from 'gray-matter';
import { readdirSync, readFileSync, statSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

interface AgentFrontmatter {
	decision_making?: { autonomy_level?: string; escalation_criteria?: string[] };
	description?: string;
	role?: string;
	specialization?: string;
}

const repoRoot = path.dirname(path.dirname(fileURLToPath(import.meta.url)));
const packagesDir = path.join(repoRoot, 'packages');
const registryPath = path.join(repoRoot, 'data', 'agents', 'registry.json');

function escalationSummary(criteria: string[] | undefined): string {
	if (!criteria || criteria.length === 0) return '_no escalation criteria declared_';
	const joined = criteria.slice(0, 2).join('; ');
	return criteria.length > 2 ? `${joined} (+${criteria.length - 2} more)` : joined;
}

function findAgentMarkdownFiles(): string[] {
	const out: string[] = [];
	for (const pkg of readdirSync(packagesDir)) {
		const agentsDir = path.join(packagesDir, pkg, 'agents');
		try {
			if (!statSync(agentsDir).isDirectory()) continue;
		} catch {
			continue;
		}
		for (const file of readdirSync(agentsDir)) {
			if (file.endsWith('.md') && !file.startsWith('_')) {
				out.push(path.join(agentsDir, file));
			}
		}
	}
	return out;
}

function loadFrontmatter(file: string): AgentFrontmatter {
	const raw = readFileSync(file, 'utf8');
	const { data } = matter(raw);
	return data as AgentFrontmatter;
}

function loadRegistryRoles(): Set<string> {
	const raw = readFileSync(registryPath, 'utf8');
	const parsed = JSON.parse(raw) as { capabilities: Record<string, unknown> };
	return new Set(Object.keys(parsed.capabilities));
}

function main(): void {
	const registryRoles = loadRegistryRoles();
	const files = findAgentMarkdownFiles().sort();
	const rows: AgentFrontmatter[] = [];
	const issues: string[] = [];

	for (const file of files) {
		const fm = loadFrontmatter(file);
		if (!fm.role) {
			issues.push(`No role in ${path.relative(repoRoot, file)}`);
			continue;
		}
		if (!registryRoles.has(fm.role)) {
			issues.push(`Role '${fm.role}' (${path.relative(repoRoot, file)}) not in registry.json`);
		}
		rows.push(fm);
	}

	for (const role of registryRoles) {
		if (!rows.find((r) => r.role === role)) {
			issues.push(`Registry role '${role}' has no agent markdown definition`);
		}
	}

	rows.sort((a, b) => (a.role ?? '').localeCompare(b.role ?? ''));

	const totalRegistry = registryRoles.size;
	const totalDefined = rows.length;

	console.log(`<!-- Generated by scripts/generate-system-card-agents.ts -->`);
	console.log(
		`<!-- Source of truth: data/agents/registry.json (${totalRegistry} agents) and packages/*/agents/*.md (${totalDefined} definitions). -->`
	);
	console.log('');
	console.log(renderTable(rows));

	if (issues.length > 0) {
		console.error('\nDrift warnings:');
		for (const issue of issues) {
			console.error(`  - ${issue}`);
		}
		process.exit(1);
	}
}

function renderTable(rows: AgentFrontmatter[]): string {
	const header = '| Agent | Specialization | Escalation criteria (first two) |';
	const sep = '| --- | --- | --- |';
	const body = rows.map((r) => {
		const role = r.role ?? '_unknown_';
		const spec = r.specialization ?? r.description ?? '—';
		const esc = escalationSummary(r.decision_making?.escalation_criteria);
		return `| \`${role}\` | ${spec} | ${esc} |`;
	});
	return [header, sep, ...body].join('\n');
}

main();
